credentials:
  usernames:
    asanchez:
      email: alex.sd2023@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Alexander Sanchez
      password: 12345 # Will be hashed automatically
    patricia:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Patricia
      password: def # Will be hashed automatically
    rodrigo:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rodrigo
      password: 12345 # Will be hashed automatically
    mariana:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Mariana
      password: 12345 # Will be hashed automatically
    Leonardo:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Leonardo
      password: 12345 # Will be hashed automatically
    
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com
